apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: tonyamoljose/apache:275
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32024
  selector:
    app: apache
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog-container
        image: tonyamoljose/catalog:275
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32025
  selector:
    app: catalog
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer-container
        image: tonyamoljose/customer:275
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32026
  selector:
    app: customer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hystrix-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
      - name: dashboard-container
        image: tonyamoljose/dashboard:275
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hystrix-dashboard
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32027
  selector:
    app: dashboard
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-container
        image: tonyamoljose/demo:275
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32028
  selector:
    app: demo
